name = "ANother fun pack"
creator = "TenBitMelon"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5b4e666181b0f6b112c7f235dcab8701bbc683f9910455cbd25a1ee8c98374c"

[versions]
minecraft = "1.21.11"
neoforge = "21.11.38-beta"