name = "ANother fun pack"
creator = "TenBitMelon"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4825fee2598f105dd1e48d10dff17b50afb60a86444a6555e89edd4544ef0f0"

[versions]
minecraft = "1.21.11"
neoforge = "21.11.38-beta"